### ISSUE TITLE
网页跨平台完美字体解决方案

### ISSUE THREAD

**Issue by lykex** [lykex/blog#2]
# 网页跨平台完美字体解决方案

> ## 向下兼容 + 优雅降级
>
> 1. 众所周知，由于 `Windows` 与其他平台（`Mac OS X`、`Linux`）的不通用性，字体渲染等问题导致在面对 **中文用户** 的时候不得不多重考虑；
> 2. 加之 *中文字体* 相对于 *英文字体* 目前仍然无法采用 `WebFont` 形式的劣势以及目前 **移动设备** 的盛行，使得我们在大呼坑爹的同时不得不忍受并适应之；
> 3. 但，有什么样的环境，就有什么样的适应法则，对于小小的 CSS `font-family` 字体，极力用好当前资源才是王道，并在其他方面提高用户体验的不足！

### 常规英文字体

Typeface		|Windows|Generic-Family	|Description
----------------|:-----:|:-------------:|-----------
`Arial`			|3.1	|sans-serif		|网页核心字体：I l 不分，跨平台，兼容！
`Tahoma`		|95		|sans-serif		|系统默认字体 && 网页核心字型：效果不错，强烈推荐！
`Verdana`		|95		|sans-serif		|网页核心字体：比 `Tahoma` 宽松一点，看个人喜好了...

### 代码等宽字体

Typeface		|Windows|Generic-Family	|Description
----------------|:-----:|:-------------:|-----------
`Courier New`	|3.1	|monospace		|网页核心字体：历史跨平台，兼容性强，字体宽松...
`Lucida Console`|98		|monospace		|系统默认字体：g * 不同 oO0 不分，字体宽松... WP [×]
`Consolas`		|Vista	|monospace		|后继核心字体：效果不错，推荐！

### 简体中文字体

Typeface			|Windows|Generic-Family	|Description
--------------------|:-----:|:-------------:|-----------
`SimSun`			|XP		|serif			|中易宋体，XP- 系统默认字体。
`Microsoft YaHei`	|Vista	|sans-serif		|微软雅黑，Vista+ 系统默认字体。

### 特殊符号图标字体

Typeface	|Windows|Description
------------|:-----:|-----------
`Symbol`	|3.1	|系统特殊符号字体。
`Wingdings`	|3.1	|系统符号图标字体。`Wingdings 2` -> `图案`	`Wingdings 3` -> `箭头`
`Webdings`	|98		|系统符号图标字体，网页核心字体。

### 常规英文字体

Typeface			|Generic-Family	|Description
--------------------|:-------------:|-----------
`Helvetica`			|sans-serif		|系统默认字体 && 广泛兼容跨平台，代替 `Windows` 下的 `Arial`
`Helvetica Neue`	|sans-serif		|系统默认字体 && 改进升级版的 `Helvetica`

### 代码等宽字体

Typeface		|Generic-Family	|Description
----------------|:-------------:|-----------
`Andale Mono`	|monospace		|等宽代码字体，网页核心字体，早期资源库字体。
`Monaco`		|monospace		|等宽代码字体，`Mac OS X v10.6 -` 默认代码字体。
`Menlo`			|monospace		|等宽代码字体，`Mac OS X v10.6 +` 默认代码字体。

### 简体中文字体

Typeface				|Chinese-Name	|Description
------------------------|:-------------:|-----------
`STHeiti`				|华文黑体		|`Mac OS X v10.6 -` 系统默认简体中文字体
`Hiragino Sans GB`		|冬青黑体		|`Mac OS X v10.6 +` 系统默认简体中文字体
`WenQuanYi Micro Hei`	|文泉驿微米黑   |`GNU` / `Linux` 发行版目前不错的中文字体

## 跨平台完美字体解决方案

1. 平台优先：`Mac OS X` -> `Linux` -> `Windows`（说明：关于移动设备 `iOS`, `Android` 无须专门设置，均可自动完美 `Fallback`。）
2. 英文优先：`Helvetica Neue` -> `Tahoma` -> `Helvetica` -> `Arial`
3. 代码字体：`Menlo` -> `Monaco` -> `Consolas` -> `Andale Mono` -> `Lucida Console` -> `Courier New`
4. 中文字体：`Hiragino Sans GB` -> `STHeiti` -> `WenQuanYi Micro Hei` -> `Microsoft YaHei` -> `SimSun`

```css
html {
	font: 14px/1.6 'Helvetica Neue', Tahoma, Helvetica, Arial, 'Hiragino Sans GB', STHeiti, 'WenQuanYi Micro Hei', 'Microsoft YaHei', SimSun, sans-serif;
}

code, kbd, pre, samp {
	/* 注意：代码字体也需要包含中文字体。 */
	font: 1em Menlo, Monaco, Consolas, 'Andale Mono', 'Lucida Console', 'Courier New', 'Hiragino Sans GB', STHeiti, 'WenQuanYi Micro Hei', 'Microsoft YaHei', SimSun, monospace;
}
```
